Markup product detail page
HIRABOU/freemarket_sample_49c pull request #18
Opened 2019-04-29 12:33 UTC by HIRABOU

# WHAT
【マークアップ】商品詳細ページ
# WHY
商品詳細ページを表示するため

2019-04-29 12:43 UTC, hiroki5123 commented
ビュー画面のキャプチャをこちらに添付してください

2019-04-29 12:45 UTC, ghost requested changes

2019-04-29 12:45 UTC, hiroki5123 commented on app/views/items/product_detail_page.html.haml
> +                = image_tag src="fig15.jpg", class:"items-photo"
srcいらないかと思います

2019-04-29 12:45 UTC, hiroki5123 commented on app/views/items/product_detail_page.html.haml
> +                = image_tag src="fig14.jpg", class:"items-photo"
こちらも

2019-04-29 12:45 UTC, hiroki5123 commented on app/views/items/product_detail_page.html.haml
> +          = link_to (image_tag src="twitter-icon.png", width:"50px", class:"twitter-icon"), "http://twitter.com/share?count=horizontal&original_referer=https%3A%2F%2Fitem.mercari.com%2Fjp%2Fm66888862
link_to doで書いてください
スタイルはCSS側に指定してください

2019-04-30 00:25 UTC, HIRABOU commented
[![Image from Gyazo](https://i.gyazo.com/c03d49ca8d8edd69a8668b735fc5880a.png)](https://gyazo.com/c03d49ca8d8edd69a8668b735fc5880a)
[![Image from Gyazo](https://i.gyazo.com/1c149f2e7b9ad5e25d9afa0408eca79b.png)](https://gyazo.com/1c149f2e7b9ad5e25d9afa0408eca79b)
[![Image from Gyazo](https://i.gyazo.com/5ebe585ac13b13b602ba939542ac9cb9.jpg)](https://gyazo.com/5ebe585ac13b13b602ba939542ac9cb9)
[![Image from Gyazo](https://i.gyazo.com/280b7936a1cf8fafb38c4fc4b548c60d.jpg)](https://gyazo.com/280b7936a1cf8fafb38c4fc4b548c60d)

2019-04-30 00:29 UTC, HIRABOU commented on app/views/items/product_detail_page.html.haml
> +                = image_tag src="fig15.jpg", class:"items-photo"
修正しました

2019-04-30 00:36 UTC, HIRABOU commented on app/views/items/product_detail_page.html.haml
> +                = image_tag src="fig14.jpg", class:"items-photo"
修正しました

2019-04-30 00:49 UTC, HIRABOU commented on app/views/items/product_detail_page.html.haml
> +          = link_to (image_tag src="twitter-icon.png", width:"50px", class:"twitter-icon"), "http://twitter.com/share?count=horizontal&original_referer=https%3A%2F%2Fitem.mercari.com%2Fjp%2Fm66888862
修正しました

2019-04-30 02:07 UTC, miyagit commented on app/assets/stylesheets/product_detail_page.scss
> +            overflow: hidden;
ここらへんBEM使えそうですね

2019-04-30 03:35 UTC, HIRABOU commented on app/assets/stylesheets/product_detail_page.scss
> +            overflow: hidden;
修正しました

2019-04-30 03:43 UTC, TOMARUMARU commented on config/routes.rb
> +  get 'items/product_detail_page' => 'items#product_detail_page'
他のところにも言えますが、resourcesで記述しましょう

2019-04-30 04:01 UTC, HIRABOU commented on config/routes.rb
> +  get 'items/product_detail_page' => 'items#product_detail_page'
実際に必要なテーブルを作成していないため、マークアップは仮置きで記述しています。
サーバーサイドで実装する際にresourcesに変更しようと考えていますが、今はそれで良いでしょうか？

2019-04-30 04:03 UTC, HIRABOU commented on config/routes.rb
> +  get 'items/product_detail_page' => 'items#product_detail_page'
あ、これはitems#showなので後で変更します

2019-04-30 04:03 UTC, TOMARUMARU commented on config/routes.rb
> +  get 'items/product_detail_page' => 'items#product_detail_page'
なるほどです、かしこまりました！

2019-04-30 04:04 UTC, TOMARUMARU approved these changes
LGTM

2019-04-30 04:08 UTC, HIRABOU commented
レビューありがとうございました

2019-04-30 05:11 UTC, merged